Repository AI-ary/backend-spring, pull requests merged in 2023-09, with the labels that each got.

#16 [chore/#13] S3 연동 및 최종 URL 저장 로직 구현
  build.gradle
  src/main/java/com/aiary/aiary/domain/diary/controller/DiaryController.java
  src/main/java/com/aiary/aiary/domain/diary/dto/mapper/DiaryMapper.java
  src/main/java/com/aiary/aiary/domain/diary/dto/request/DiaryCreateRequest.java
  src/main/java/com/aiary/aiary/domain/diary/service/DiaryService.java
  src/main/java/com/aiary/aiary/global/config/S3Config.java
  src/main/java/com/aiary/aiary/global/result/ResultCode.java
  src/main/java/com/aiary/aiary/global/s3/controller/S3Controller.java
  src/main/java/com/aiary/aiary/global/s3/service/S3UploadService.java
Labels: 환경설정

#18 [feat/#17] 제목/내용에 포함된 keyword 검색 시 일기 조회
  src/main/java/com/aiary/aiary/domain/diary/controller/DiaryController.java
  src/main/java/com/aiary/aiary/domain/diary/dto/mapper/DiaryMapper.java
  src/main/java/com/aiary/aiary/domain/diary/dto/response/SearchDiariesRes.java
  src/main/java/com/aiary/aiary/domain/diary/repository/DiaryRepository.java
  src/main/java/com/aiary/aiary/domain/diary/service/DiaryService.java
  src/main/java/com/aiary/aiary/domain/user/entity/UserDetail.java
Labels: 기능구현

#22 [feat/#21] 사용자 테마 변경 API 작성
  src/main/java/com/aiary/aiary/domain/diary/entity/Weather.java
  src/main/java/com/aiary/aiary/domain/user/controller/UserController.java
  src/main/java/com/aiary/aiary/domain/user/dto/request/UserThemeReq.java
  src/main/java/com/aiary/aiary/domain/user/dto/response/UserProfileRes.java
  src/main/java/com/aiary/aiary/domain/user/entity/Theme.java
  src/main/java/com/aiary/aiary/domain/user/entity/User.java
  src/main/java/com/aiary/aiary/domain/user/mapper/UserMapper.java
  src/main/java/com/aiary/aiary/domain/user/service/UserService.java
  src/main/java/com/aiary/aiary/global/jwt/JwtTokenProvider.java
  src/main/java/com/aiary/aiary/global/result/ResultCode.java
Labels: 기능구현

#24 [refactor/#23] 변수명, dto 형식 일치
  .github/workflows/google-java-format.yml
  src/main/java/com/aiary/aiary/domain/diary/controller/DiaryController.java
  src/main/java/com/aiary/aiary/domain/diary/dto/mapper/DiaryMapper.java
  src/main/java/com/aiary/aiary/domain/diary/dto/request/DiaryCreateReq.java
  src/main/java/com/aiary/aiary/domain/diary/dto/response/DiaryRes.java
  src/main/java/com/aiary/aiary/domain/diary/dto/response/MonthlyDiaryRes.java
  src/main/java/com/aiary/aiary/domain/diary/dto/response/SearchDiariesRes.java
  src/main/java/com/aiary/aiary/domain/diary/repository/DiaryRepository.java
  src/main/java/com/aiary/aiary/domain/diary/service/DiaryService.java
  src/main/java/com/aiary/aiary/domain/user/controller/UserController.java
  src/main/java/com/aiary/aiary/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/aiary/aiary/domain/user/dto/request/UserJoinReq.java
  src/main/java/com/aiary/aiary/domain/user/dto/request/UserLoginReq.java
  src/main/java/com/aiary/aiary/domain/user/dto/request/UserTokenReq.java
  src/main/java/com/aiary/aiary/domain/user/entity/UserDetail.java
  src/main/java/com/aiary/aiary/domain/user/service/AuthService.java
  src/main/java/com/aiary/aiary/domain/user/service/CustomUserDetailService.java
  src/main/java/com/aiary/aiary/domain/user/service/UserService.java
  src/main/java/com/aiary/aiary/domain/user/validator/UserValidator.java
  src/main/java/com/aiary/aiary/global/config/SecurityConfig.java
  src/main/java/com/aiary/aiary/global/jwt/JwtToken.java
Labels: 리팩토링

#28 [feat/#27] 프로필 이미지 변경 API (S3 이미지 삭제 후 업로드)
  src/main/java/com/aiary/aiary/domain/diary/controller/DiaryController.java
  src/main/java/com/aiary/aiary/domain/user/controller/UserController.java
  src/main/java/com/aiary/aiary/domain/user/dto/mapper/UserMapper.java
  src/main/java/com/aiary/aiary/domain/user/dto/response/UserProfileRes.java
  src/main/java/com/aiary/aiary/domain/user/entity/User.java
  src/main/java/com/aiary/aiary/domain/user/entity/UserDetail.java
  src/main/java/com/aiary/aiary/domain/user/service/UserService.java
  src/main/java/com/aiary/aiary/global/config/SecurityConfig.java
  src/main/java/com/aiary/aiary/global/result/ResultCode.java
  src/main/java/com/aiary/aiary/global/s3/controller/S3Controller.java
  src/main/java/com/aiary/aiary/global/s3/service/S3Service.java
  src/main/java/com/aiary/aiary/global/s3/service/S3UploadService.java
Labels: 기능구현
